{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-xslt
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xslt_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xslt/xslt_{{ version }}.tar.gz
  sha256: 8aa8af768eba0c719f6de04df137f584ec27dcf1c92d10a9b0cebb51c7aeff94

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-xml2 >=1.3.0               # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("c") }}            # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
    - r-xml2 >=1.3.0
    - libiconv                     # [win]
    - libxml2
    - libxslt
    - zlib                         # [win]
  run:
    - r-base
    - r-rcpp
    - r-xml2 >=1.3.0

test:
  requires:
    - r-testthat
  commands:
    - $R -e "library('xslt')"                          # [not win]
    - $R -e "testthat::test_package('xslt')"           # [not win]
    - "\"%R%\" -e \"library('xslt')\""                 # [win]
    - "\"%R%\" -e \"testthat::test_package('xslt')\""  # [win]

about:
  home: https://ropensci.r-universe.dev/xslt
  doc_url: https://docs.ropensci.org/xslt/
  license: GPL-2.0-or-later
  summary: An extension for the 'xml2' package to transform XML documents by applying an 'xslt' style-sheet.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - TanguyGen
